### PR TITLE
Add support for react context from react@~16.6.0

### LINKED ISSUE #45: Fix new Context handling (react@^16.6.x)
As of react 16.6 the both Provider and Consumer types has `_context` property, which leads to context  loss whenever we are visiting Consumer:

```js
if (currentElement.type._context) {
  // eslint-disable-next-line no-param-reassign
  currentElement.type._context._currentValue =
    currentElement.props.value
}
```

The most naive way to fix it is to check whether we actually have `value` prop. There is more advanced approach here: https://github.com/jaydenseric/graphql-react/compare/v3.0.0...v4.0.1#diff-3e6d5558503509cddfcf7ef1bc7ee575

Here is a demo of an error: https://codesandbox.io/s/o4wrj5m0jy

### PR DESCRIPTION
**Pull request by SleepWalker**
Closes #45 

See #45 for details

### CODE REVIEW

**Comment by SleepWalker** [comment]
@ctrlplusb can you please look at this PR. It is really important, because without it it is impossible to use react-tree-walker with context from react@16.6.x

**Comment by ctrlplusb** [comment]
Thanks for this @SleepWalker!!

**Comment by jcampalo** [comment]
Please release this.

**Comment by oyeanuj** [comment]
@jcampalo @dan-lee @SleepWalker Are you maintaining a released fork of this by any chance?

**Comment by SleepWalker** [comment]
I'm using a local copy with help of yarn workspaces. I can publish it on
npm, but I'm not sure, that I'll be active enough to support it :)

**Comment by exah** [comment]
@oyeanuj you can install `@exah/react-tree-walker` with included fix, but I will likely copy depended code from package in future.

**Pull request merged**
